"""Generate the console's response types from the control plane's OpenAPI schema.

The design specifies that `console/src/lib/api.ts` is generated. It was
hand-written, and that cost two defects in one session: the Operations view
declared `/pipeline` as `runs: [...]` on an endpoint that returns a single
`run`, and the Audit view declared `message` where the server sends `reason`.
Neither failed loudly — the fetch returned 200, the query reported success, and
`tsc` type-checked an assertion nobody had compared to the server.

Generation was impossible until `api/app/contracts.py` existed. Every handler
returned a bare `dict`, so FastAPI emitted `{"type": "object"}` with no
properties for 47 of 53 operations, and a generator over that emits
`Record<string, unknown>` for everything — worse than the hand-written types it
would have replaced.

Reads the schema from a running control plane rather than from a checked-in
copy, for the same reason `check_console_contract.py` does: a committed
`contracts/openapi/` file is a claim about the server, and the server is the
thing the console has to agree with.

    python tools/generate_console_types.py [--base-url URL] [--out PATH] [--check]

`--check` regenerates in memory and exits 1 if the committed file differs, so CI
fails on a schema change nobody regenerated for.
"""

from __future__ import annotations

import argparse
import difflib
import json
import pathlib
import re
import sys
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_OUT = ROOT / "console" / "src" / "lib" / "api-types.ts"

HEADER = """// Generated by tools/generate_console_types.py — do not edit.
//
// Every type here is the control plane's own declared response schema, read
// from its OpenAPI document. Hand-editing a type in this file makes it a claim
// about the server again, which is the failure this file exists to remove:
// `/pipeline` was declared as `runs: [...]` against an endpoint returning one
// `run`, and nothing failed — the fetch returned 200 and `tsc` checked the
// assertion rather than the contract.
//
// Regenerate with the stack up:
//     python tools/generate_console_types.py
//
// Fields are optional where the schema does not require them. `unknown` appears
// where a handler's own declaration is untyped, and is honest: it means the
// server has not said, not that the value is absent.

"""


def fetch(url: str) -> dict:
    with urllib.request.urlopen(url, timeout=15) as r:
        return json.loads(r.read().decode())


def ts_name(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "", name)


def ts_type(schema: dict, spec: dict, depth: int = 0) -> str:
    """One JSON Schema node as a TypeScript type."""
    if depth > 12:
        return "unknown"
    if not schema:
        return "unknown"

    if "$ref" in schema:
        return ts_name(schema["$ref"].rsplit("/", 1)[-1])

    for key in ("anyOf", "oneOf"):
        if key in schema:
            parts = [ts_type(s, spec, depth + 1) for s in schema[key]]
            # Pydantic renders an optional as anyOf[T, null].
            parts = ["null" if p == "unknown" and s.get("type") == "null" else p
                     for p, s in zip(parts, schema[key])]
            uniq = list(dict.fromkeys(parts))
            return " | ".join(uniq)

    if "allOf" in schema and len(schema["allOf"]) == 1:
        return ts_type(schema["allOf"][0], spec, depth + 1)

    t = schema.get("type")
    if t == "array":
        item = ts_type(schema.get("items") or {}, spec, depth + 1)
        # `A | B[]` means A-or-array-of-B. JSON Schema's array of a union is
        # `(A | B)[]`, and the parentheses are semantically required.
        if " | " in item:
            item = f"({item})"
        return f"{item}[]"
    if t == "string":
        if schema.get("enum"):
            return " | ".join(json.dumps(e) for e in schema["enum"])
        return "string"
    if t == "integer" or t == "number":
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "object":
        add = schema.get("additionalProperties")
        if isinstance(add, dict):
            return f"Record<string, {ts_type(add, spec, depth + 1)}>"
        if schema.get("properties"):
            inner = ", ".join(
                f"{json.dumps(k)}{'' if k in schema.get('required', []) else '?'}: "
                f"{ts_type(v, spec, depth + 1)}"
                for k, v in schema["properties"].items())
            return "{ " + inner + " }"
        return "Record<string, unknown>"
    return "unknown"


def emit_interface(name: str, schema: dict, spec: dict) -> str:
    props = schema.get("properties") or {}
    required = set(schema.get("required") or [])
    lines = [f"export interface {ts_name(name)} {{"]
    if not props:
        lines.append("  [key: string]: unknown;")
    for k, v in props.items():
        opt = "" if k in required else "?"
        key = k if re.match(r"^[A-Za-z_$][A-Za-z0-9_$]*$", k) else json.dumps(k)
        lines.append(f"  {key}{opt}: {ts_type(v, spec)};")
    # Do not mirror Pydantic's ``extra=allow`` as an index signature. The server
    # uses that setting to avoid filtering a response at runtime; carrying it
    # into TypeScript makes every misspelled property legal. That hid
    # ``owner_resolved`` in the Operations view even though the route has never
    # returned such a field. Additive response fields remain safe in structural
    # typing without weakening every declared consumer to ``unknown``.
    lines.append("}")
    return "\n".join(lines)


def route_map(spec: dict) -> str:
    """path+method -> response type, so a caller can look the type up by route."""
    rows = []
    for path, methods in sorted(spec["paths"].items()):
        for method, op in sorted(methods.items()):
            sch = (((op.get("responses") or {}).get("200") or {})
                   .get("content", {}).get("application/json", {}).get("schema")) or {}
            name = ts_type(sch, spec)
            rows.append(f'  {json.dumps(method.upper() + " " + path)}: {name};')
    return "export interface ApiRoutes {\n" + "\n".join(rows) + "\n}"


def generate(base_url: str) -> str:
    spec = fetch(base_url.rstrip("/") + "/openapi.json")
    schemas = (spec.get("components") or {}).get("schemas") or {}

    out = [HEADER]
    for name in sorted(schemas):
        out.append(emit_interface(name, schemas[name], spec))
        out.append("")
    out.append(route_map(spec))
    out.append("")
    return "\n".join(out)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--base-url", default="http://localhost:8080")
    p.add_argument("--out", default=str(DEFAULT_OUT))
    p.add_argument("--check", action="store_true",
                   help="fail if the committed file differs from what the server implies")
    a = p.parse_args()

    try:
        text = generate(a.base_url)
    except (urllib.error.URLError, OSError, json.JSONDecodeError) as exc:
        print(f"UNREACHABLE  {a.base_url} — {exc}", file=sys.stderr)
        print("Nothing was generated. This is not a pass.", file=sys.stderr)
        return 2

    out = pathlib.Path(a.out)
    if a.check:
        current = out.read_text() if out.exists() else ""
        if current != text:
            print(f"FAIL  {out} is stale against {a.base_url}")
            for line in list(difflib.unified_diff(
                    current.splitlines(), text.splitlines(),
                    "committed", "generated", lineterm=""))[:40]:
                print("  " + line)
            return 1
        print(f"OK  {out} matches the schema the control plane declares.")
        return 0

    out.write_text(text)
    n = text.count("export interface ")
    print(f"OK  {n} interfaces written to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
