"""Regulatory clause mapping — rule-based, never model-generated.

A clause citation must be exactly right. This is not a place for generation, so
the mapping is a table of predicates and every citation names the field that
triggered it. A compliance officer can check the finding rather than trust it.

Seven frameworks. FFIEC DA&M is in the grid because it is the entire stated
rationale for human-in-the-loop remediation at stage 10; the source document
cited it in prose while omitting it from the list and claiming six.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

from sentry_core.enums import DataClass, Governance, Lifecycle

VERSION = "fw-1.0.0"

FRAMEWORKS = (
    "RBI API Security 2023",
    "PCI-DSS v4.0",
    "DPDP Act 2023",
    "FFIEC DA&M",
    "NYDFS Part 500",
    "DORA (EU)",
    "FS AI RMF",
)


@dataclass(frozen=True)
class Rule:
    framework: str
    clause: str
    requirement: str
    predicate: Callable[[dict], bool]
    evidence: Callable[[dict], str]


def _has(ctx: dict, *classes: DataClass) -> bool:
    s = set(ctx.get("data_classes") or [])
    return bool(s & {c.value for c in classes})


RULES: tuple[Rule, ...] = (
    Rule(
        "RBI API Security 2023", "Section 4.2", "Authentication enforcement",
        lambda c: c.get("auth") in ("none", "basic"),
        lambda c: f"auth = {c.get('auth')}",
    ),
    Rule(
        "RBI API Security 2023", "Section 5.1", "Transport encryption",
        lambda c: c.get("tls_version") in (None, "", "1.0", "1.1"),
        lambda c: f"tls_version = {c.get('tls_version') or 'none'}",
    ),
    Rule(
        "RBI API Security 2023", "Continuous monitoring mandate",
        "Inventory and monitoring of all interfaces",
        lambda c: c.get("lifecycle") == Lifecycle.ZOMBIE.value,
        lambda c: "lifecycle = ZOMBIE",
    ),
    Rule(
        "PCI-DSS v4.0", "Req 6.3", "Secure development lifecycle",
        lambda c: _has(c, DataClass.CARD, DataClass.CVV),
        lambda c: f"data_classes contains {sorted(set(c.get('data_classes') or []) & {'CARD','CVV'})}",
    ),
    Rule(
        "PCI-DSS v4.0", "Req 6.4", "Public-facing application protection",
        lambda c: bool(c.get("internet_reachable")) and not c.get("rate_limited"),
        lambda c: "internet reachable with no rate limiting",
    ),
    Rule(
        "DPDP Act 2023", "Section 8", "Data minimisation",
        lambda c: _has(c, DataClass.PAN, DataClass.AADHAAR, DataClass.ACCOUNT_NO, DataClass.DOB),
        lambda c: f"data_classes contains {sorted(c.get('data_classes') or [])}",
    ),
    Rule(
        "FFIEC DA&M", "Development, Acquisition & Maintenance",
        "Ownership and authorised change control",
        lambda c: c.get("governance") in (Governance.ORPHANED.value, Governance.SHADOW.value),
        lambda c: f"governance = {c.get('governance')}",
    ),
    Rule(
        "NYDFS Part 500", "Section 500.12", "MFA / privileged access control",
        lambda c: c.get("auth") == "none" and c.get("lifecycle") == Lifecycle.ZOMBIE.value,
        lambda c: "unauthenticated zombie endpoint",
    ),
    Rule(
        "NYDFS Part 500", "Section 500.06", "Audit trail",
        lambda c: True,  # the ledger is the standing evidence for every finding
        lambda c: "SENTRY hash-chained audit ledger",
    ),
    Rule(
        "DORA (EU)", "Article 9", "Protection and prevention",
        lambda c: c.get("governance") == Governance.SHADOW.value
        or c.get("blast_tier") == "CRITICAL",
        lambda c: f"governance = {c.get('governance')}, blast = {c.get('blast_tier')}",
    ),
    Rule(
        "FS AI RMF", "AI decision logging", "Explainable, auditable AI decisions",
        lambda c: c.get("generator") == "anthropic",
        lambda c: "narrative generated by model; ai_decision row written",
    ),
)


def map_findings(ctx: dict) -> list[dict]:
    """Return every citation whose predicate matches, with its evidence."""
    out: list[dict] = []
    for r in RULES:
        try:
            if r.predicate(ctx):
                out.append({
                    "framework": r.framework,
                    "clause": r.clause,
                    "requirement": r.requirement,
                    "status": "VIOLATED" if r.clause != "Section 500.06" else "SATISFIED",
                    "evidence": r.evidence(ctx),
                })
        except Exception:  # a malformed context must not lose every other citation
            continue
    return out


def coverage(contexts: list[dict]) -> dict[str, int]:
    counts = {f: 0 for f in FRAMEWORKS}
    for ctx in contexts:
        for cite in map_findings(ctx):
            if cite["status"] == "VIOLATED":
                counts[cite["framework"]] = counts.get(cite["framework"], 0) + 1
    return counts
