// Generated by tools/generate_console_types.py — do not edit.
//
// Every type here is the control plane's own declared response schema, read
// from its OpenAPI document. Hand-editing a type in this file makes it a claim
// about the server again, which is the failure this file exists to remove:
// `/pipeline` was declared as `runs: [...]` against an endpoint returning one
// `run`, and nothing failed — the fetch returned 200 and `tsc` checked the
// assertion rather than the contract.
//
// Regenerate with the stack up:
//     python tools/generate_console_types.py
//
// Fields are optional where the schema does not require them. `unknown` appears
// where a handler's own declaration is untyped, and is honest: it means the
// server has not said, not that the value is absent.


export interface AdvanceBody {
  reason: string;
  [key: string]: unknown;
}

export interface ApplyBody {
  control_id: number;
  [key: string]: unknown;
}

export interface Audit {
  items: AuditItemsItem[];
  next_cursor: number;
  [key: string]: unknown;
}

export interface AuditItemsItem {
  seq: number;
  wall_ts: string;
  vday: number;
  actor: string;
  action: string;
  target: string;
  detail: Record<string, unknown>;
  entry_hash: string;
  [key: string]: unknown;
}

export interface AuditVerify {
  ok: boolean;
  entries: number;
  broken_at?: number | null;
  reason?: string | null;
  [key: string]: unknown;
}

export interface Baseline {
  vday: number;
  registry_size: number;
  confidence: BaselineConfidence;
  growth: BaselineGrowthItem[];
  verdicts_permitted: boolean;
  decommission_permitted: number;
  [key: string]: unknown;
}

export interface BaselineConfidence {
  PROVISIONAL: number;
  CONFIRMED: number;
  [key: string]: unknown;
}

export interface BaselineEndpointIdSeries {
  endpoint_id: string;
  series: BaselineEndpointIdSeriesSeriesItem[];
  [key: string]: unknown;
}

export interface BaselineEndpointIdSeriesSeriesItem {
  vday: number;
  calls: number;
  errors: number;
  p95_latency_us?: number | null;
  [key: string]: unknown;
}

export interface BaselineGrowthItem {
  vday: number;
  n: number;
  [key: string]: unknown;
}

export interface Behaviour {
  fitted: boolean;
  fitted_on: number;
  min_fit_endpoints: number;
  withheld?: string | null;
  flagged: number;
  scored: number;
  patterns: BehaviourPatterns;
  excluded_insufficient_history: number;
  items: BehaviourItemsItem[];
  [key: string]: unknown;
}

export interface BehaviourItemsItem {
  endpoint_id: string;
  score: number;
  isolation_depth: number;
  patterns: unknown[];
  [key: string]: unknown;
}

export interface BehaviourPatterns {
  INSUFFICIENT_HISTORY: number;
  [key: string]: unknown;
}

export interface Classification {
  vday: number;
  matrix: ClassificationMatrixItem[];
  confidence: ClassificationConfidence;
  shadow_reliable: boolean;
  [key: string]: unknown;
}

export interface ClassificationConfidence {
  PROVISIONAL: number;
  CONFIRMED: number;
  [key: string]: unknown;
}

export interface ClassificationEndpointId {
  endpoint_id: string;
  lifecycle: string;
  governance: string;
  confidence: string;
  severity_bump: boolean;
  pre_zombie: boolean;
  trace: ClassificationEndpointIdTraceItem[];
  vday: number;
  engine_version: string;
  [key: string]: unknown;
}

export interface ClassificationEndpointIdTraceItem {
  q: number;
  question: string;
  answer: number;
  source: string;
  [key: string]: unknown;
}

export interface ClassificationMatrixItem {
  lifecycle: string;
  governance: string;
  n: number;
  [key: string]: unknown;
}

export interface Clock {
  vday: number;
  scale_seconds: number;
  paused: boolean;
  epoch_wall: string;
  real_time: boolean;
  [key: string]: unknown;
}

export interface ClockPause {
  vday: number;
  paused: boolean;
  [key: string]: unknown;
}

export interface ClockResume {
  vday: number;
  paused: boolean;
  [key: string]: unknown;
}

export interface ClockSetInput {
  vday: number;
  [key: string]: unknown;
}

export interface ClockSetOutput {
  vday: number;
  previous: number;
  [key: string]: unknown;
}

export interface Correlation {
  sightings: number;
  endpoints: number;
  dedup_ratio: number;
  ownership: CorrelationOwnership;
  shadow_reliable: boolean;
  window_vdays: number;
  [key: string]: unknown;
}

export interface CorrelationEndpointIdOwnership {
  endpoint_id: string;
  owner_email: string;
  owner_team?: string | null;
  resolved_by: string;
  confidence: number;
  reachable: boolean;
  escalation: string;
  ladder: CorrelationEndpointIdOwnershipLadderItem[];
  [key: string]: unknown;
}

export interface CorrelationEndpointIdOwnershipLadderItem {
  rung: string;
  result: string;
  [key: string]: unknown;
}

export interface CorrelationOwnership {
  resolved_by: Record<string, number>;
  unreachable: number;
  [key: string]: unknown;
}

export interface Decommission {
  vday: number;
  by_phase: DecommissionByPhase;
  items: DecommissionItemsItem[];
  [key: string]: unknown;
}

export interface DecommissionByPhase {
  C: number;
  RETIRED: number;
  [key: string]: unknown;
}

export interface DecommissionEndpointIdAdvance {
  endpoint_id: string;
  from_phase: string;
  released_by: string;
  note: string;
  [key: string]: unknown;
}

export interface DecommissionEndpointIdEnrol {
  endpoint_id: string;
  phase: string;
  express: boolean;
  canary: boolean;
  [key: string]: unknown;
}

export interface DecommissionEndpointIdHold {
  endpoint_id: string;
  hold: boolean;
  reason?: string | null;
  [key: string]: unknown;
}

export interface DecommissionEndpointIdWormVerify {
  object: string;
  version_id: string;
  lock_mode: string;
  retain_until: string;
  verified: boolean;
  delete_refused_with: string;
  detail: string;
  [key: string]: unknown;
}

export interface DecommissionItemsItem {
  endpoint_id: string;
  method: string;
  path: string;
  phase: string;
  express: boolean;
  canary: boolean;
  canary_split?: number | null;
  entered_vday: number;
  phase_vday: number;
  hold: boolean;
  hold_reason?: string | null;
  hidden_callers: DecommissionItemsItemHiddenCallersItem[];
  worm_object?: string | null;
  worm_retain_until?: string | null;
  certificate_id?: string | null;
  [key: string]: unknown;
}

export interface DecommissionItemsItemHiddenCallersItem {
  service: string;
  ip: string;
  first_vday: number;
  calls: number;
  [key: string]: unknown;
}

export interface Discovery {
  vday: number;
  sources: DiscoverySourcesItem[];
  shadow_reliable: boolean;
  shadow_count: number;
  [key: string]: unknown;
}

export interface DiscoverySourcesItem {
  source: string;
  endpoints: number;
  observations_24v: number;
  exclusive: number;
  healthy: boolean;
  [key: string]: unknown;
}

export interface Estate {
  items: EstateItemsItem[];
  next_cursor?: number | null;
  [key: string]: unknown;
}

export interface EstateEndpointId {
  id: string;
  method: string;
  path: string;
  service: EstateEndpointIdService;
  auth: string;
  tls_version?: string | null;
  rate_limited: boolean;
  data_classes: string[];
  deprecated: boolean;
  internet_reachable: boolean;
  retired: boolean;
  honeypot_active: boolean;
  first_vday: number;
  last_call_vday: number;
  total_calls: number;
  sources: string[];
  classification: EstateEndpointIdClassification;
  cdri: EstateEndpointIdCdri;
  anomaly: EstateEndpointIdAnomaly;
  forecast: EstateEndpointIdForecast;
  blast: EstateEndpointIdBlast;
  ownership: EstateEndpointIdOwnership;
  [key: string]: unknown;
}

export interface EstateEndpointIdAnomaly {
  flag: boolean;
  score: number;
  patterns: unknown[];
  features: Record<string, number>;
  [key: string]: unknown;
}

export interface EstateEndpointIdBlast {
  tier: string;
  direct_callers: number;
  hop2_callers: number;
  touches_critical: boolean;
  in_graph: boolean;
  hop_limit: number;
  affected: EstateEndpointIdBlastAffectedItem[];
  [key: string]: unknown;
}

export interface EstateEndpointIdBlastAffectedItem {
  service_id: string;
  name: string;
  hop: number;
  calls: number;
  criticality: string;
  [key: string]: unknown;
}

export interface EstateEndpointIdCdri {
  score: number;
  tier: string;
  parts: EstateEndpointIdCdriPartsItem[];
  weights_version: number;
  time_to_breach: EstateEndpointIdCdriTimeToBreach;
  [key: string]: unknown;
}

export interface EstateEndpointIdCdriPartsItem {
  key: string;
  label: string;
  r: number;
  w: number;
  contribution: number;
  [key: string]: unknown;
}

export interface EstateEndpointIdCdriTimeToBreach {
  days: number;
  basis: string;
  factors: string[];
  [key: string]: unknown;
}

export interface EstateEndpointIdClassification {
  lifecycle: string;
  governance: string;
  confidence: string;
  pre_zombie: boolean;
  severity_bump: boolean;
  trace: EstateEndpointIdClassificationTraceItem[];
  [key: string]: unknown;
}

export interface EstateEndpointIdClassificationTraceItem {
  q: number;
  question: string;
  answer: number;
  source: string;
  [key: string]: unknown;
}

export interface EstateEndpointIdForecast {
  days_to_zombie?: number | null;
  slope: number;
  signals: Record<string, number>;
  deseasonalised: boolean;
  [key: string]: unknown;
}

export interface EstateEndpointIdOwnership {
  owner_email: string;
  reachable: boolean;
  confidence: number;
  resolved_by: string;
  escalation: string;
  ladder: EstateEndpointIdOwnershipLadderItem[];
  [key: string]: unknown;
}

export interface EstateEndpointIdOwnershipLadderItem {
  rung: string;
  result: string;
  [key: string]: unknown;
}

export interface EstateEndpointIdService {
  id: string;
  name: string;
  team: string;
  criticality: string;
  [key: string]: unknown;
}

export interface EstateItemsItem {
  id: string;
  method: string;
  path: string;
  service: string;
  team: string;
  criticality: string;
  auth: string;
  tls_version?: string | null;
  rate_limited: boolean;
  data_classes: string[];
  last_call_vday: number;
  retired: boolean;
  lifecycle: string;
  governance: string;
  confidence: string;
  pre_zombie: boolean;
  cdri: number;
  tier: string;
  time_to_breach_d: number;
  [key: string]: unknown;
}

export interface Findings {
  generators: FindingsGenerators;
  items: FindingsItemsItem[];
  [key: string]: unknown;
}

export interface FindingsFrameworks {
  frameworks: string[];
  violations: Record<string, unknown>;
  [key: string]: unknown;
}

export interface FindingsGenerators {
  template: number;
  [key: string]: unknown;
}

export interface FindingsItemsItem {
  id: string;
  endpoint_id: string;
  method: string;
  path: string;
  generator: string;
  model?: string | null;
  narrative: FindingsItemsItemNarrative;
  regulations: FindingsItemsItemRegulationsItem[];
  time_to_breach_d: number;
  vday: number;
  [key: string]: unknown;
}

export interface FindingsItemsItemNarrative {
  summary: string;
  technical: string;
  action: string;
  [key: string]: unknown;
}

export interface FindingsItemsItemRegulationsItem {
  framework: string;
  clause: string;
  requirement: string;
  status: string;
  evidence: string;
  [key: string]: unknown;
}

export interface Forecast {
  flagged: number;
  active: number;
  flagged_ratio: number;
  items: ForecastItemsItem[];
  [key: string]: unknown;
}

export interface ForecastEndpointId {
  endpoint_id: string;
  days_to_zombie?: number | null;
  slope: number;
  level: number;
  signals: Record<string, number>;
  deseasonalised: boolean;
  observed: number[];
  adjusted: number[];
  projection: number[];
  [key: string]: unknown;
}

export interface ForecastItemsItem {
  endpoint_id: string;
  method: string;
  path: string;
  days_to_zombie: number;
  slope: number;
  signals: Record<string, number>;
  deseasonalised: boolean;
  [key: string]: unknown;
}

export interface GateCheck {
  repo: string;
  pr_number: number;
  commit_sha: string;
  routes: Record<string, unknown>[];
  [key: string]: unknown;
}

export interface GateCheckResult {
  passed: boolean;
  checks: Record<string, unknown>[];
  [key: string]: unknown;
}

export interface GateEvents {
  events: GateEventsEventsItem[];
  [key: string]: unknown;
}

export interface GateEventsEventsItem {
  id: number;
  repo: string;
  pr: number;
  sha: string;
  passed: boolean;
  checks: GateEventsEventsItemChecksItem[];
  at: string;
  [key: string]: unknown;
}

export interface GateEventsEventsItemChecksItem {
  name: string;
  passed: boolean;
  severity: string;
  file: string;
  line: number;
  [key: string]: unknown;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
  [key: string]: unknown;
}

export interface HardenPreviewBody {
  endpoint_id: string;
  [key: string]: unknown;
}

export interface HoldBody {
  reason: string;
  hold?: boolean;
  [key: string]: unknown;
}

export interface ImpactEndpointId {
  endpoint_id: string;
  tier: string;
  hop_limit: number;
  direct_callers: number;
  hop2_callers: number;
  touches_critical: boolean;
  in_graph: boolean;
  datastores: unknown[];
  affected: ImpactEndpointIdAffectedItem[];
  retirement_path: ImpactEndpointIdRetirementPath;
  [key: string]: unknown;
}

export interface ImpactEndpointIdAffectedItem {
  service_id: string;
  name: string;
  hop: number;
  calls: number;
  criticality: string;
  [key: string]: unknown;
}

export interface ImpactEndpointIdRetirementPath {
  express: boolean;
  canary: boolean;
  phases: string[];
  estimated_vdays: number;
  throttle_exempt: boolean;
  [key: string]: unknown;
}

export interface Live {
  vday: number;
  scale_seconds: number;
  observed: Record<string, number>;
  source: string;
  counters: Record<string, number>;
  health: LiveHealthItem[];
  pipeline: LivePipeline;
  [key: string]: unknown;
}

export interface LiveHealthItem {
  component: string;
  state: string;
  last_vday?: number | null;
  vdays_behind?: number | null;
  [key: string]: unknown;
}

export interface LivePipeline {
  run_id?: number | null;
  trigger?: string | null;
  started_at?: unknown;
  ok?: boolean | null;
  running: boolean;
  stages_done: number;
  stages_total: number;
  [key: string]: unknown;
}

export interface Operations {
  vday: number;
  scan_interval_vhours: number;
  scheduler_enabled: boolean;
  siem: OperationsSiem;
  stages: Record<string, unknown>;
  gate_events: OperationsGateEventsItem[];
  [key: string]: unknown;
}

export interface OperationsGateEventsItem {
  repo: string;
  pr: number;
  sha: string;
  passed: boolean;
  checks: OperationsGateEventsItemChecksItem[];
  at: string;
  [key: string]: unknown;
}

export interface OperationsGateEventsItemChecksItem {
  name: string;
  passed: boolean;
  severity: string;
  file: string;
  line: number;
  [key: string]: unknown;
}

export interface OperationsLeaderboard {
  teams: OperationsLeaderboardTeamsItem[];
  [key: string]: unknown;
}

export interface OperationsLeaderboardTeamsItem {
  team: string;
  debt: number;
  raw: number;
  trend?: string | null;
  endpoints: number;
  zombies: number;
  orphaned: number;
  pre_zombie: number;
  critical_score: number;
  ownership_confidence: number;
  [key: string]: unknown;
}

export interface OperationsScan {
  run_id: number;
  stages: OperationsScanStagesItem[];
  [key: string]: unknown;
}

export interface OperationsScanStagesItem {
  stage: number;
  records: number;
  duration_ms: number;
  error?: string | null;
  skipped?: string | null;
  [key: string]: unknown;
}

export interface OperationsSiem {
  host: string;
  format: string;
  configured: boolean;
  port: number;
  sent: number;
  spooled: number;
  dropped: number;
  failures: number;
  recent: unknown[];
  [key: string]: unknown;
}

export interface Pipeline {
  vday: number;
  run: PipelineRun;
  stages: PipelineStagesItem[];
  order: number[];
  [key: string]: unknown;
}

export interface PipelineRun {
  id: number;
  trigger: string;
  started_at: string;
  finished_at: string;
  ok: boolean;
  [key: string]: unknown;
}

export interface PipelineStagesItem {
  stage: number;
  name: string;
  depends_on: unknown[];
  ok: boolean;
  records: number;
  duration_ms: number;
  error?: string | null;
  [key: string]: unknown;
}

export interface PolicySettings {
  settings: PolicySettingsSettings;
  warnings: unknown[];
  [key: string]: unknown;
}

export interface PolicySettingsKey {
  key: string;
  value?: unknown;
  [key: string]: unknown;
}

export interface PolicySettingsSettings {
  latency_budget_us: Record<string, number>;
  tier_bounds: Record<string, number>;
  resurrection_threshold: PolicySettingsSettingsResurrectionThreshold;
  blast_hop_limit: PolicySettingsSettingsBlastHopLimit;
  scan_interval_vhours: PolicySettingsSettingsScanIntervalVhours;
  express_sunset_vdays: PolicySettingsSettingsExpressSunsetVdays;
  anomaly_contamination: PolicySettingsSettingsAnomalyContamination;
  honeypot_legal_signoff: PolicySettingsSettingsHoneypotLegalSignoff;
  [key: string]: unknown;
}

export interface PolicySettingsSettingsAnomalyContamination {
  value: number;
  [key: string]: unknown;
}

export interface PolicySettingsSettingsBlastHopLimit {
  value: number;
  [key: string]: unknown;
}

export interface PolicySettingsSettingsExpressSunsetVdays {
  value: number;
  [key: string]: unknown;
}

export interface PolicySettingsSettingsHoneypotLegalSignoff {
  reference: string;
  signed: boolean;
  [key: string]: unknown;
}

export interface PolicySettingsSettingsResurrectionThreshold {
  value: number;
  [key: string]: unknown;
}

export interface PolicySettingsSettingsScanIntervalVhours {
  value: number;
  [key: string]: unknown;
}

export interface PolicyWeights {
  version: number;
  weights: Record<string, number>;
  sum: number;
  defaults: Record<string, number>;
  history: PolicyWeightsHistoryItem[];
  [key: string]: unknown;
}

export interface PolicyWeightsHistoryItem {
  version: number;
  weights: Record<string, number>;
  note: string;
  created_by: string;
  created_at: string;
  [key: string]: unknown;
}

export interface PolicyWeightsReset {
  version: number;
  weights: Record<string, number>;
  [key: string]: unknown;
}

export interface Remediation {
  items: RemediationItemsItem[];
  [key: string]: unknown;
}

export interface RemediationControlControlIdRevert {
  control_id: number;
  state: string;
  also_reverted?: number[];
  [key: string]: unknown;
}

export interface RemediationEndpointId {
  endpoint_id: string;
  controls: RemediationEndpointIdControlsItem[];
  change_request: RemediationEndpointIdChangeRequest;
  [key: string]: unknown;
}

export interface RemediationEndpointIdApply {
  control_id: number;
  state: string;
  kong_plugin_id?: string | null;
  superseded_control_id?: number | null;
  [key: string]: unknown;
}

export interface RemediationEndpointIdChangeRequest {
  number?: string | null;
  state: string;
  sys_id?: string | null;
  stub: boolean;
  [key: string]: unknown;
}

export interface RemediationEndpointIdControlsItem {
  id: number;
  kind: string;
  state: string;
  generator: string;
  plugin_config: RemediationEndpointIdControlsItemPluginConfig;
  kong_plugin_id: string;
  origin_stage: number;
  error?: string | null;
  actor: string;
  judge?: Record<string, unknown> | null;
  [key: string]: unknown;
}

export interface RemediationEndpointIdControlsItemPluginConfig {
  name: string;
  config: RemediationEndpointIdControlsItemPluginConfigConfig;
  [key: string]: unknown;
}

export interface RemediationEndpointIdControlsItemPluginConfigConfig {
  status_code: number;
  message: string;
  [key: string]: unknown;
}

export interface RemediationItemsItem {
  endpoint_id: string;
  method: string;
  path: string;
  score: number;
  tier: string;
  time_to_breach_d: number;
  controls: unknown[];
  applied: number;
  [key: string]: unknown;
}

export interface Risk {
  items: RiskItemsItem[];
  [key: string]: unknown;
}

export interface RiskItemsItem {
  endpoint_id: string;
  method: string;
  path: string;
  score: number;
  tier: string;
  parts: RiskItemsItemPartsItem[];
  weights_version: number;
  time_to_breach: RiskItemsItemTimeToBreach;
  [key: string]: unknown;
}

export interface RiskItemsItemPartsItem {
  key: string;
  label: string;
  r: number;
  w: number;
  contribution: number;
  [key: string]: unknown;
}

export interface RiskItemsItemTimeToBreach {
  days: number;
  basis: string;
  factors: string[];
  [key: string]: unknown;
}

export interface SettingUpdate {
  value: Record<string, unknown>;
  [key: string]: unknown;
}

export interface System {
  org: string;
  vday: number;
  endpoints: number;
  retired: number;
  lifecycle: Record<string, number>;
  governance: Record<string, number>;
  tiers: SystemTiers;
  mean_cdri: number;
  [key: string]: unknown;
}

export interface SystemTiers {
  HIGH: number;
  CRITICAL: number;
  [key: string]: unknown;
}

export interface Threat {
  honeypots_active: number;
  probes_total: number;
  unique_sources: number;
  fingerprints: number;
  threshold: number;
  legal_signoff: ThreatLegalSignoff;
  probes: ThreatProbesItem[];
  alerts: ThreatAlertsItem[];
  [key: string]: unknown;
}

export interface ThreatAlertsItem {
  new_endpoint_id: string;
  origin_path: string;
  similarity: number;
  threshold: number;
  lsh_hit: boolean;
  vday: number;
  [key: string]: unknown;
}

export interface ThreatFingerprintEndpointId {
  endpoint_id: string;
  captured_vday: number;
  origin_path: string;
  origin_method: string;
  features: ThreatFingerprintEndpointIdFeatures;
  shingles: string[];
  shingle_count: number;
  [key: string]: unknown;
}

export interface ThreatFingerprintEndpointIdFeatures {
  method: string;
  response_fields: unknown[];
  data_classes: string[];
  callers: string[];
  hour_shape: number[];
  auth: string;
  auth_missing_band: string;
  req_size_band: string;
  resp_size_band: string;
  observations: number;
  has_schema: boolean;
  [key: string]: unknown;
}

export interface ThreatLegalSignoff {
  reference: string;
  signed: boolean;
  [key: string]: unknown;
}

export interface ThreatProbes {
  count: number;
  probes: ThreatProbesProbesItem[];
  [key: string]: unknown;
}

export interface ThreatProbesItem {
  id: number;
  at: string;
  vday: number;
  endpoint_id: string;
  source_ip: string;
  source_asn?: string | null;
  watermark: string;
  [key: string]: unknown;
}

export interface ThreatProbesProbesItem {
  id: number;
  at: string;
  vday: number;
  endpoint_id: string;
  method: string;
  path_raw: string;
  source_ip: string;
  source_asn?: string | null;
  geo?: string | null;
  headers: ThreatProbesProbesItemHeaders;
  watermark: string;
  session_fp: string;
  body_sha256?: string | null;
  [key: string]: unknown;
}

export interface ThreatProbesProbesItemHeaders {
  Accept: string;
  Connection: string;
  "User-Agent"?: string;
  Via: string;
  "X-Forwarded-For"?: string;
  "X-Forwarded-Host"?: string;
  "X-Forwarded-Path"?: string;
  "X-Forwarded-Port"?: string;
  "X-Forwarded-Proto"?: string;
  "X-Kong-Request-Id"?: string;
  "X-Real-Ip"?: string;
  [key: string]: unknown;
}

export interface ThreatRescan {
  vday: number;
  alerts_raised: number;
  [key: string]: unknown;
}

export interface ThreatResurrectionScan {
  fingerprints: number;
  threshold: number;
  alerts: ThreatResurrectionScanAlertsItem[];
  [key: string]: unknown;
}

export interface ThreatResurrectionScanAlertsItem {
  new_endpoint_id: string;
  new_endpoint: string;
  origin_endpoint_id: string;
  origin_path: string;
  similarity: number;
  threshold: number;
  lsh_hit: boolean;
  vday: number;
  created_at: string;
  [key: string]: unknown;
}

export interface ValidationError {
  loc: string | number[];
  msg: string;
  type: string;
  [key: string]: unknown;
}

export interface WeightsUpdate {
  weights: Record<string, number>;
  note?: string | null;
  [key: string]: unknown;
}

export interface Zerotrust {
  distribution: Record<string, unknown>;
  gaps: Record<string, number>;
  items: ZerotrustItemsItem[];
  [key: string]: unknown;
}

export interface ZerotrustEndpointId {
  endpoint_id: string;
  satisfied: number;
  of: number;
  priority: number;
  controls: ZerotrustEndpointIdControlsItem[];
  method: string;
  path: string;
  [key: string]: unknown;
}

export interface ZerotrustEndpointIdControlsItem {
  key: string;
  ok: boolean;
  current: string;
  remedy: string;
  requires_migration: boolean;
  [key: string]: unknown;
}

export interface ZerotrustEndpointIdHarden {
  endpoint_id: string;
  posture: Record<string, unknown>;
  would_apply?: Record<string, unknown>[] | null;
  controls?: Record<string, unknown>[] | null;
  blocked?: string | null;
  [key: string]: unknown;
}

export interface ZerotrustHardenPreview {
  endpoint_id: string;
  posture: Record<string, unknown>;
  would_apply?: Record<string, unknown>[] | null;
  controls?: Record<string, unknown>[] | null;
  blocked?: string | null;
  [key: string]: unknown;
}

export interface ZerotrustItemsItem {
  endpoint_id: string;
  method: string;
  path: string;
  satisfied: number;
  of: number;
  priority: number;
  controls: ZerotrustItemsItemControlsItem[];
  [key: string]: unknown;
}

export interface ZerotrustItemsItemControlsItem {
  key: string;
  ok: boolean;
  current: string;
  remedy: string;
  requires_migration: boolean;
  [key: string]: unknown;
}

export interface ApiRoutes {
  "GET /api/v1/audit": Audit;
  "GET /api/v1/audit/verify": AuditVerify;
  "GET /api/v1/baseline": Baseline;
  "GET /api/v1/baseline/{endpoint_id}/series": BaselineEndpointIdSeries;
  "GET /api/v1/behaviour": Behaviour;
  "GET /api/v1/classification": Classification;
  "GET /api/v1/classification/{endpoint_id}": ClassificationEndpointId;
  "GET /api/v1/clock": Clock;
  "POST /api/v1/clock/pause": ClockPause;
  "POST /api/v1/clock/resume": ClockResume;
  "POST /api/v1/clock/set": ClockSetOutput;
  "GET /api/v1/correlation": Correlation;
  "GET /api/v1/correlation/{endpoint_id}/ownership": CorrelationEndpointIdOwnership;
  "GET /api/v1/decommission": Decommission;
  "POST /api/v1/decommission/{endpoint_id}/advance": DecommissionEndpointIdAdvance;
  "POST /api/v1/decommission/{endpoint_id}/enrol": DecommissionEndpointIdEnrol;
  "POST /api/v1/decommission/{endpoint_id}/hold": DecommissionEndpointIdHold;
  "GET /api/v1/decommission/{endpoint_id}/worm/verify": DecommissionEndpointIdWormVerify;
  "GET /api/v1/discovery": Discovery;
  "GET /api/v1/estate": Estate;
  "GET /api/v1/estate/{endpoint_id}": EstateEndpointId;
  "GET /api/v1/findings": Findings;
  "GET /api/v1/findings/frameworks": FindingsFrameworks;
  "GET /api/v1/forecast": Forecast;
  "GET /api/v1/forecast/{endpoint_id}": ForecastEndpointId;
  "POST /api/v1/gate/check": GateCheckResult;
  "GET /api/v1/gate/events": GateEvents;
  "GET /api/v1/impact/{endpoint_id}": ImpactEndpointId;
  "GET /api/v1/live": Live;
  "GET /api/v1/operations": Operations;
  "GET /api/v1/operations/leaderboard": OperationsLeaderboard;
  "POST /api/v1/operations/scan": OperationsScan;
  "GET /api/v1/operations/siem": OperationsSiem;
  "GET /api/v1/pipeline": Pipeline;
  "GET /api/v1/policy/settings": PolicySettings;
  "PUT /api/v1/policy/settings/{key}": PolicySettingsKey;
  "GET /api/v1/policy/weights": PolicyWeights;
  "POST /api/v1/policy/weights": PolicyWeights;
  "POST /api/v1/policy/weights/reset": PolicyWeightsReset;
  "GET /api/v1/remediation": Remediation;
  "POST /api/v1/remediation/control/{control_id}/revert": RemediationControlControlIdRevert;
  "GET /api/v1/remediation/{endpoint_id}": RemediationEndpointId;
  "POST /api/v1/remediation/{endpoint_id}/apply": RemediationEndpointIdApply;
  "GET /api/v1/risk": Risk;
  "GET /api/v1/system": System;
  "GET /api/v1/threat": Threat;
  "GET /api/v1/threat/fingerprint/{endpoint_id}": ThreatFingerprintEndpointId;
  "GET /api/v1/threat/probes": ThreatProbes;
  "POST /api/v1/threat/rescan": ThreatRescan;
  "GET /api/v1/threat/resurrection-scan": ThreatResurrectionScan;
  "GET /api/v1/zerotrust": Zerotrust;
  "POST /api/v1/zerotrust/harden-preview": ZerotrustHardenPreview;
  "GET /api/v1/zerotrust/{endpoint_id}": ZerotrustEndpointId;
  "POST /api/v1/zerotrust/{endpoint_id}/harden": ZerotrustEndpointIdHarden;
}
